name: ov-device-props # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Get device properties using OpenVINO
description: |
  This snap reports the GOPS performance of all devices detected and usable by OpenVINO.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  my-app:
    plugin: python
    source: .
    python-packages:
      - openvino
    stage-packages:
      - clinfo
      - intel-opencl-icd
    override-build: |
      craftctl default
      cp show_device_properties.py $SNAPCRAFT_PART_INSTALL/

apps:
  ov-device-props:
    plugs:
      - hardware-observe
      - opengl
      - network
    command: show_device_properties.py
